name: Docker Push

on:
  push:
    tags:
      - 'snowpost-*'

jobs:
    deploy-user:
        runs-on: ubuntu-latest
        permissions:
          packages: write
          contents: read
        strategy:
          matrix:
            arch:
              - linux/amd64
              - linux/arm64
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: get version
          run: echo 'TAG='${GITHUB_REF#refs/tags/} >> $GITHUB_ENV
    
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
    
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: snowpost
            push: true
            pull: true
            tags: |
                ghcr.io/npelikan/snowpost:latest
                ghcr.io/npelikan/snowpost:${{ github.ref_name }}
                ghcr.io/npelikan/snowpost:${{ env.TAG }}
            platforms: ${{ matrix.arch }}
            cache-from: type=gha
            cache-to: type=gha,mode=max